# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Start dev containers
        run: |
          docker compose -f docker-compose.dev.yml up -d
          sleep 10

      - name: Run DB migrations
        run: |
          make migrate-postgresql

      - name: Generates code and test data
        run: make generate-all

      - name: Build
        run: go build -v ./...

      - name: Test

        run: make go-test
